steps:
  # Build the Docker image with build arguments from Secret Manager
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=$$SUPABASE_URL'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=$$SUPABASE_ANON_KEY'
      - '--build-arg'
      - 'GEMINI_API_KEY=$$GEMINI_API_KEY'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ckn-bookapp:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ckn-bookapp:latest'
      - '.'
    secretEnv: ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'GEMINI_API_KEY']
  
  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ckn-bookapp:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ckn-bookapp:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ckn-nutrition-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ckn-bookapp:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_SUPABASE_URL=$$SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY=$$SUPABASE_ANON_KEY,GEMINI_API_KEY=$$GEMINI_API_KEY'
    secretEnv: ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'GEMINI_API_KEY']

# Secret Manager configuration - no substitutions needed!
# The secrets are referenced directly from Secret Manager
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/supabase-url/versions/latest
    env: 'SUPABASE_URL'
  - versionName: projects/$PROJECT_ID/secrets/supabase-anon-key/versions/latest
    env: 'SUPABASE_ANON_KEY'
  - versionName: projects/$PROJECT_ID/secrets/gemini-api-key/versions/latest
    env: 'GEMINI_API_KEY'

# Timeout for the entire build (default is 10 minutes)
timeout: '1200s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ckn-bookapp:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ckn-bookapp:latest'
